### PR TITLE
feat(cli): unhide query and policy commands

### PR DESCRIPTION
**Pull request by hazedav**
Hide query sources
Hide query describe
Enable integration tests

ALLY-584

### CODE REVIEW

**Review by afiune — COMMENTED** [review]
This is a huge milestone, @hazedav !!! Kuddos to you for all the work you have done.

Having said that, we need to really add more useful information to the Short and Long descriptions so that customers can look at the help of the command and know what to do right there, rather than having to look for the documentation on support.lacework.com

A few examples you can follow are:
```
lacework compliance -h
Manage compliance reports for Google, Azure, or AWS cloud providers.

Lacework cloud security platform provides continuous Compliance monitoring against
cloud security best practices and compliance standards as CIS, PCI DSS, SoC II and
HIPAA benchmark standards.

Get started by integrating one or more cloud accounts using the command:

    $ lacework integration create

If you prefer to configure the integration via the WebUI, log in to your account at:

    https://<ACCOUNT>.lacework.net

Then navigate to Settings > Integrations > Cloud Accounts.

Use the following command to list all available integrations in your account:

    $ lacework integrations list

Usage:
  lacework compliance [command]

Aliases:
  compliance, comp

Available Commands:
  aws         compliance for AWS
  azure       compliance for Azure Cloud
  google      compliance for Google Cloud

Flags:
  -h, --help   help for compliance

Global Flags:
  -a, --account string      account subdomain of URL (i.e. <ACCOUNT>.lacework.net)
  -k, --api_key string      access key id
  -s, --api_secret string   secret access key
      --debug               turn on debug logging
      --json                switch commands output from human-readable to json format
      --nocache             turn off caching
      --nocolor             turn off colors
      --noninteractive      turn off interactive mode (disable spinners, prompts, etc.)
      --organization        access organization level data sets (org admins only)
  -p, --profile string      switch between profiles configured at ~/.lacework.toml
      --subaccount string   sub-account name inside your organization (org admins only)

Use "lacework compliance [command] --help" for more information about a command.
```
or:
```
lacework configure -h
Configure settings that the Lacework CLI uses to interact with the Lacework
platform. These include your Lacework account, API access key and secret.

To create a set of API keys, log in to your Lacework account via WebUI and
navigate to Settings > API Keys and click + Create New. Enter a name for
the key and an optional description, then click Save. To get the secret key,
download the generated API key file.

Use the flag --json_file to preload the downloaded API key file.

If this command is run with no flags, the Lacework CLI will store all
settings under the default profile. The information in the default profile
is used any time you run a Lacework CLI command that doesn't explicitly
specify a profile to use.

You can configure multiple profiles by using the --profile flag. If a
config file does not exist (the default location is ~/.lacework.toml),
the Lacework CLI will create it for you.

Usage:
  lacework configure [flags]
  lacework configure [command]

Available Commands:
  list        list all configured profiles at ~/.lacework.toml
  show        show current configuration data

Flags:
  -h, --help               help for configure
  -j, --json_file string   loads the API key JSON file downloaded from the WebUI

Global Flags:
  -a, --account string      account subdomain of URL (i.e. <ACCOUNT>.lacework.net)
  -k, --api_key string      access key id
  -s, --api_secret string   secret access key
      --debug               turn on debug logging
      --json                switch commands output from human-readable to json format
      --nocache             turn off caching
      --nocolor             turn off colors
      --noninteractive      turn off interactive mode (disable spinners, prompts, etc.)
      --organization        access organization level data sets (org admins only)
  -p, --profile string      switch between profiles configured at ~/.lacework.toml
      --subaccount string   sub-account name inside your organization (org admins only)

Use "lacework configure [command] --help" for more information about a command.
```

**Comment by hazedav** [comment]
> Having said that, we need to really add more useful information to the Short and Long descriptions so that customers can look at the help of the command and know what to do right there, rather than having to look for the documentation on support.lacework.com

Couldn't agree more.

cc @davymcaleer  as this will require more sdk cycles in addition to getting the integration tests to pass

**Comment by davymcaleer** [comment]
@hazedav @afiune can we add a backlog item in JIRA to track/cover this ?

**Comment by hazedav** [comment]
Tests are likely to fail here until we are able to merge:
https://github.com/lacework/go-sdk/pull/501

**Comment by hazedav** [comment]
FWIW tests are passing as-is on dev7:

```
Setting up host tests
=== RUN   TestPolicyHelp
--- PASS: TestPolicyHelp (0.46s)
=== RUN   TestPolicyBase
--- PASS: TestPolicyBase (0.01s)
=== RUN   TestPolicyCreateHelp
--- PASS: TestPolicyCreateHelp (0.31s)
=== RUN   TestPolicyCreateEditor
--- PASS: TestPolicyCreateEditor (0.80s)
=== RUN   TestPolicyCreateFile
--- PASS: TestPolicyCreateFile (8.03s)
=== RUN   TestPolicyCreateURL
--- PASS: TestPolicyCreateURL (4.42s)
=== RUN   TestPolicyListHelp
--- PASS: TestPolicyListHelp (0.32s)
=== RUN   TestPolicyList
--- PASS: TestPolicyList (1.49s)
=== RUN   TestPolicyBadSeverity
--- PASS: TestPolicyBadSeverity (0.67s)
=== RUN   TestPolicySeverityCritical
--- PASS: TestPolicySeverityCritical (0.76s)
=== RUN   TestPolicyShowHelp
--- PASS: TestPolicyShowHelp (0.34s)
=== RUN   TestPolicyShow
--- PASS: TestPolicyShow (1.47s)
=== RUN   TestPolicyUpdateHelp
--- PASS: TestPolicyUpdateHelp (0.32s)
=== RUN   TestPolicyUpdateEditor
--- PASS: TestPolicyUpdateEditor (0.63s)
=== RUN   TestPolicyUpdateFile
--- PASS: TestPolicyUpdateFile (0.00s)
=== RUN   TestPolicyUpdateURL
--- PASS: TestPolicyUpdateURL (0.00s)
=== RUN   TestPolicyDeleteHelp
--- PASS: TestPolicyDeleteHelp (0.32s)
=== RUN   TestPolicyDeleteNoInput
--- PASS: TestPolicyDeleteNoInput (0.31s)
=== RUN   TestPolicyDelete
--- PASS: TestPolicyDelete (3.31s)
PASS
ok      github.com/lacework/go-sdk/integration  28.644s
```

**Review by afiune — APPROVED** [review]
Let's do this!

tenor-167497005

**Pull request merged**
