### PR TITLE
Updated URL in Resource Groups v2 command help text

### PR DESCRIPTION
**Pull request by ggaetz-fortinet**
## Summary
Corrected URL in help text to point to public API documentation.

### CODE REVIEW

**Comment by goodmorninggoaway** [comment]
@ggaetz-fortinet  If you're waiting on reviews, post the PR in https://lacework.slack.com/archives/C05UD0RH6GJ

**Comment by ggaetz-fortinet** [comment]
I don't have access to Lacework Slack.

**Comment by goodmorninggoaway** [comment]
> I don't have access to Lacework Slack.

That explains why I couldn't find you. You can request access via global helpdesk

**Comment by PengyuanZhao** [comment]
@ggaetz-fortinet please change the commit message to follow https://www.conventionalcommits.org/en/v1.0.0/. In that way, your commit will be picked up and shown in the release notes.

**Comment by sushmadittakavilacework** [comment]
> @ggaetz-fortinet please change the commit message to follow https://www.conventionalcommits.org/en/v1.0.0/. In that way, your commit will be picked up and shown in the release notes.

Nice to see the commitmessage lint failure to catch this.

**Comment by ggaetz-fortinet** [comment]
I fixed the commit message lint error but I'm not sure if or how to fix the lint error due to the long URL.

**Comment by sushmadittakavilacework** [comment]
> I fixed the commit message lint error but I'm not sure if or how to fix the lint error due to the long URL.

I dont know why there is a character limit. Does it need to be broken into two lines..? @PengyuanZhao do you know?

**Comment by PengyuanZhao** [comment]
Yes, it would need to break into two lines. If using vscode, the `Go` plugin should be installed. It will automatically give hints and format the code.

**Comment by ggaetz-fortinet** [comment]
I fixed the linting errors so now it should be good, as long as the integration tests are ok. 

Thanks for your patience.

**Pull request merged**
