### PR TITLE
chore: bump go version to 1.21

### PR DESCRIPTION
**Pull request by dmurray-lacework**
## Summary

Update required go version to go.1.21
Update golanglint-ci version
Make fmting/style changes for go.1.21

## How did you test this change?

Run developer test pipeline

## Issue

https://lacework.atlassian.net/browse/GROW-1596

### CODE REVIEW

**Comment by dmurray-lacework** [comment]
developer test

**Comment by dmurray-lacework** [comment]
developer test

**Comment by dmurray-lacework** [comment]
developer test

**Comment by dmurray-lacework** [comment]
developer test

**Comment by dmurray-lacework** [comment]
developer test

**Comment by dmurray-lacework** [comment]
developer test

**Comment by dmurray-lacework** [comment]
developer test

**Comment by dmurray-lacework** [comment]
developer test

**Comment by dmurray-lacework** [comment]
developer test

**Comment by dmurray-lacework** [comment]
developer test

**Comment by dmurray-lacework** [comment]
developer test

**Review by jon-stewart — APPROVED** [review]

**Comment by dmurray-lacework** [comment]
developer test

**Pull request merged**
