### PR TITLE
feat(cli): sort query and policy list output

### PR DESCRIPTION
**Pull request by hazedav**
## Summary
As a Lacework user, I would like the `lacework query ls`, `lacework query sources`, `lacework policy ls`, and `lacework policy list-tags` outputs to be sorted such that I can easily find items that I’m looking for

## How did you test this change?
Manually tested
Integration tested

## Issue
https://lacework.atlassian.net/browse/ALLY-910

### CODE REVIEW

**Review by afiune — APPROVED** [review]
What about policies?

**Comment by hazedav** [comment]
> What about policies?

The ticket was scoped down to just queries.  We can certainly address policies as well; but:

1.  since they mostly contain integers the sorting is slightly more complex.
2.  it wasn't clear if we want to sort policies by severity or by id

So we need some guidance as to whether we want sort by severity, id, severity-then-id, or `id-then-severity` and for any id based sorting whether we want `lwcustom-34` to come before `lwcustom-4` in the list...

David

**Comment by afiune** [comment]
@hazedav wasn't involved in the scoping but, it makes sense! 🙌🏽

**Comment by hazedav** [comment]
> @hazedav wasn't involved in the scoping but, it makes sense! 🙌🏽

@andrewelizondo / @afiune do you want to weigh in on how you want policies sorted or you just want me to do it by ID and handle the integers?

**Comment by andrewelizondo** [comment]
Since we have a different mechanism to sort/organize policies it should probably be done separately, for datasets we really only have namespace which makes this the best approach currently. LGTM 👍

**Comment by hazedav** [comment]
@afiune I went ahead and added `policy ls` sort...

**Review by andrewelizondo — APPROVED** [review]

**Comment by hazedav** [comment]
@afiune gave me a verbal OK on this.

**Pull request merged**
