### PR TITLE
ci: test on windows systems 

### PR DESCRIPTION
**Pull request by afiune**
## User Story

As a Lacework Engineer,
I want to test the Lacework CLI in Windows systems,
So I can verify compatibility of every change I deliver

## Summary

Create a pipeline that uses the new Windows system in Codefresh to run the Lacework CLI integration tests.

## How did you test this change?

Created a new pipeline and run it:

Screen Shot 2021-12-21 at 9 05 03 PM

## Issue

https://lacework.atlassian.net/browse/ALLY-803

### CODE REVIEW

**Comment by afiune** [comment]
This change is actually uncovering some real failures!

```
=== Errors                                                                                                                                          
Reading environment variable exporting file contents.                                                                                               
integration\configure_windows_test.go:28:6: TestConfigureCommandWithJSONFileFlagError redeclared in this block                                      
        C:\codefresh\volume\go-sdk\integration\configure_unix_test.go:529:51: previous declaration                                                  
integration\configure_windows_test.go:41:6: TestConfigureListHelp redeclared in this block                                                          
        C:\codefresh\volume\go-sdk\integration\configure_unix_test.go:542:31: previous declaration  
```

**Comment by afiune** [comment]
Check windows!!

**Review by ipcrm — APPROVED** [review]

**Comment by afiune** [comment]
check windows again!! 🙌🏽

**Comment by afiune** [comment]
Check Windows one last time!

**Pull request merged**
