### PR TITLE
fix(ci) Update CI test node

### PR DESCRIPTION
**Pull request by scottford-lw**
Updating persistent Circle CI test node for host vulnerability testing. 

Signed-off-by: Scott Ford <scott.ford@lacework.net>

### CODE REVIEW

**Comment by scottford-lw** [comment]
@afiune the integration test is failing because the hostname is not matching the test. On the node the `hostname` and `hostname -f` both return `circle-ci-test-node`. In the UI the node shows up at `circle-ci-test-node`, but `lacework vul host show-assessment 30` returns a hostname of `ip-10-0-1-170.us-west-2.compute.internal`. 

Obviously we can update the test to match the response, but I am not clear what is causing the mis-match. Let me know if you have thoughts.

**Comment by afiune** [comment]
@scottford-lw great catch! This is definitely a bug. I'll go check on the backend and in the meantime, I will open an issue.

**Comment by afiune** [comment]
Bug ticket created: **RAIN-13990**

Let's omit to check for the hostname for now.

**Review by afiune — APPROVED** [review]
tenor-262859852

**Pull request merged**
