### PR TITLE
test(cli): Add comprehensive help text testing

### PR DESCRIPTION
**Pull request by hazedav**
## Summary
This PR adds canonical help output for all CLI commands which is programmatically validated

## How did you test this change?
Full integration testing

## Issue
https://lacework.atlassian.net/browse/ALLY-902

### CODE REVIEW

**Comment by afiune** [comment]
Check windows! 👀

**Review by afiune — COMMENTED** [review]
## I freacking looooove this!!!!

tenor-196034842

**Comment by hazedav** [comment]
Check windows! 👀

Expected difference that we'll need to account for:
```
   -    $env:LW_PROFILE = 'my-profile'
   +    export LW_PROFILE="my-profile"
```

**Comment by hazedav** [comment]
Windows integration is happy happy joy joy:
https://g.codefresh.io/build/621e5339e41322fb1d732be8

**Comment by hazedav** [comment]
@afiune we good here?

**Comment by afiune** [comment]
Check windows!! 🪟

**Review by afiune — APPROVED** [review]
tenor-231798196

**Comment by hazedav** [comment]
Thanks for the review bud!

**Pull request merged**
